### ISSUE TITLE
forward() got an unexpected keyword argument 'alpha'

### ISSUE THREAD

**Issue by Manishroy1205** [swag-kaust/dda_pytorch#1]
![image](https://user-images.githubusercontent.com/76405048/172117751-216a4d84-35f6-435f-9f96-17a65544167a.png)

After uploading file and the datset still getting issues with the keyword 'alpha'

**Comment by ovcharenkoo** [comment]
Hi @Manishroy1205, which notebook is that?

**Comment by ovcharenkoo** [comment]
Fixed, the error was in `ex2_cnn.ipynb` where I forgot to remove the old piece of code. 

Thank you for the catch!
